"""add verified_at to identities

Revision ID: c4ae1e6d2cd0
Revises: 9b903196c188
Create Date: 2026-02-17 22:42:01.320529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ae1e6d2cd0'
down_revision: Union[str, None] = '9b903196c188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_tokens', sa.Column('token_hash', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index('ix_email_verify_identity_active', 'email_verification_tokens', ['identity_id', 'expires_at'], unique=False)
    op.drop_column('email_verification_tokens', 'token')
    op.add_column('identities', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_tokens', sa.Column('replaced_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_last_used_at'), 'refresh_tokens', ['last_used_at'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'refresh_tokens', ['replaced_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_last_used_at'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'replaced_by_id')
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('identities', 'verified_at')
    op.add_column('email_verification_tokens', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index('ix_email_verify_identity_active', table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.drop_column('email_verification_tokens', 'token_hash')
    # ### end Alembic commands ###
